### ISSUE TITLE
Math question (dominating measure)

### ISSUE THREAD

**Issue by ekernf01** [amcdavid/HurdleNormal#2]
Hey Andrew! I found your paper on this, which is really cool, and I want to try to understand it despite my being rusty on statistics. When you say the dominating measure comes from "adding a Dirac mass at zero to the Lebesgue measure", do you mean adding a point mass at the origin, or adding masses to all planes that have some zeroes fixed? Thanks!

**Comment by amcdavid** [comment]
The latter.  We end up with a product measure of Lebesgue + dirac at zero.  Section 3.1 has more of the details.
