### ISSUE TITLE
Installing HurdleNormal

### ISSUE THREAD

**Issue by galaxywall** [amcdavid/HurdleNormal#4]
**I was trying to install HurdleNormal from GitHub using the following command: devtools::install_github("amcdavid/HurdleNormal",dependencies = T) and got the following error message. Could you please help me figure out what is wrong?**

Skipping 3 packages not available: MAST, Mus.musculus, netbenchmark
Installing 20 packages: gridExtra, xfun, checkmate, jpeg, png, viridis, htmlTable, acepack, latticeExtra, Formula, RcppEigen, quadprog, Cairo, dtplyr, GGally, Hmisc, MAST, Mus.musculus, huge, directlabels
Installing packages into ‘C:/Users/galaxywall/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
Error: Failed to install 'HurdleNormal' from GitHub:
  (converted from warning) packages ‘MAST’, ‘Mus.musculus’ are not available (for R version 3.6.2)

**Also, to later intsall netbenchmark, Mus.musculus from Bioconductor, should I simply use a command like: BiocManager::install('netbenchmark')?**

**Comment by amcdavid** [comment]
Yes, that's correct. Those packages are on bioconductor and will need to be
installed as you indicated. I will update the Readme to make the clear.
Thanks for the report.

**Comment by galaxywall** [comment]
Thanks. Do you have an idea why I got the error message when installing HurdleNormal from GitHub?

**Comment by amcdavid** [comment]
Looks like devtools doesn't know about bioconductor repositories.  `BiocManager::install('amcdavid/HurdleNormal')` should install from github and knows about both cran and bioconductor.

FWIW, I don't think you have to set `dependencies = TRUE` unless you want to reproduce code from the paper or run some components of the vignette.

**Comment by galaxywall** [comment]
**Eh, I tried your command and ended up with the following error. And I got the same error as I used my original command without setting dependencies = T.**

> BiocManager::install("amcdavid/HurdleNormal")
Bioconductor version 3.10 (BiocManager 1.30.10), R 3.6.2 (2019-12-12)
Installing github package(s) 'amcdavid/HurdleNormal'
Downloading GitHub repo amcdavid/HurdleNormal@HEAD
√  checking for file 'C:\Users\galaxywall\AppData\Local\Temp\RtmpWIcfig\remotes2f4c4e613893\amcdavid-HurdleNormal-f91e584/DESCRIPTION' (593ms)
-  preparing 'HurdleNormal':
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
   Removed empty directory 'HurdleNormal/inst/aoas_simulations'
   Removed empty directory 'HurdleNormal/inst'
-  looking to see if a 'data/datalist' file should be added
-  building 'HurdleNormal_0.98.7.tar.gz'
   
* installing *source* package 'HurdleNormal' ...
** using staged installation
** libs

*** arch - i386
C:/RBuildTools/3.5/mingw_32/bin/g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-36~1.2/include" -DNDEBUG  -I"C:/Users/galaxywall/Documents/R/win-library/3.6/RcppArmadillo/include" -I"C:/Users/galaxywall/Documents/R/win-library/3.6/Rcpp/include"        -O2 -Wall  -mtune=generic -c hurdle_distributions.cpp -o hurdle_distributions.o
C:/RBuildTools/3.5/mingw_32/bin/g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-36~1.2/include" -DNDEBUG  -I"C:/Users/galaxywall/Documents/R/win-library/3.6/RcppArmadillo/include" -I"C:/Users/galaxywall/Documents/R/win-library/3.6/Rcpp/include"        -O2 -Wall  -mtune=generic -c hurdle_likelihood.cpp -o hurdle_likelihood.o
C:/RBuildTools/3.5/mingw_32/bin/g++ -std=gnu++11 -shared -s -static-libgcc -o HurdleNormal.dll tmp.def hurdle_distributions.o hurdle_likelihood.o -LC:/PROGRA~1/R/R-36~1.2/bin/i386 -lR
hurdle_likelihood.o:hurdle_likelihood.cpp:(.text+0x3e02): undefined reference to `dgemv_'
hurdle_likelihood.o:hurdle_likelihood.cpp:(.text+0x3ef2): undefined reference to `dgemv_'
hurdle_likelihood.o:hurdle_likelihood.cpp:(.text$_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_3MatIdEENS_3ColIdEEEEvRNS3_INT_9elem_typeEEERKNS_4GlueIS7_T0_NS_10glue_timesEEE[__ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_3MatIdEENS_3ColIdEEEEvRNS3_INT_9elem_typeEEERKNS_4GlueIS7_T0_NS_10glue_timesEEE]+0x12d): undefined reference to `dgemv_'
hurdle_likelihood.o:hurdle_likelihood.cpp:(.text$_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_3MatIdEENS_3ColIdEEEEvRNS3_INT_9elem_typeEEERKNS_4GlueIS7_T0_NS_10glue_timesEEE[__ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_3MatIdEENS_3ColIdEEEEvRNS3_INT_9elem_typeEEERKNS_4GlueIS7_T0_NS_10glue_timesEEE]+0x2d7): undefined reference to `dgemv_'
hurdle_likelihood.o:hurdle_likelihood.cpp:(.text$_ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_3MatIdEENS_3ColIdEEEEvRNS3_INT_9elem_typeEEERKNS_4GlueIS7_T0_NS_10glue_timesEEE[__ZN4arma27glue_times_redirect2_helperILb0EE5applyINS_3MatIdEENS_3ColIdEEEEvRNS3_INT_9elem_typeEEERKNS_4GlueIS7_T0_NS_10glue_timesEEE]+0x5b8): undefined reference to `dgemv_'
hurdle_likelihood.o:hurdle_likelihood.cpp:(.text$_ZN4arma4gemvILb1ELb0ELb0EE15apply_blas_typeIdNS_3MatIdEEEEvPT_RKT0_PKS5_S5_S5_[__ZN4arma4gemvILb1ELb0ELb0EE15apply_blas_typeIdNS_3MatIdEEEEvPT_RKT0_PKS5_S5_S5_]+0xc6): more undefined references to `dgemv_' follow
hurdle_likelihood.o:hurdle_likelihood.cpp:(.text$_ZN4arma10glue_times5applyIdLb1ELb0ELb0ENS_3MatIdEES3_EEvRNS2_IT_EERKT3_RKT4_S4_[__ZN4arma10glue_times5applyIdLb1ELb0ELb0ENS_3MatIdEES3_EEvRNS2_IT_EERKT3_RKT4_S4_]+0x17a): undefined reference to `dgemm_'
hurdle_likelihood.o:hurdle_likelihood.cpp:(.text$_ZN4arma10glue_times5applyIdLb1ELb0ELb0ENS_3MatIdEES3_EEvRNS2_IT_EERKT3_RKT4_S4_[__ZN4arma10glue_times5applyIdLb1ELb0ELb0ENS_3MatIdEES3_EEvRNS2_IT_EERKT3_RKT4_S4_]+0x397): undefined reference to `dsyrk_'
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'HurdleNormal'
* removing 'C:/Users/galaxywall/Documents/R/win-library/3.6/HurdleNormal'
Error: Failed to install 'HurdleNormal' from GitHub:
  (converted from warning) installation of package ‘C:/Users/GALAXY~1/AppData/Local/Temp/RtmpWIcfig/file2f4c23a079ab/HurdleNormal_0.98.7.tar.gz’ had non-zero exit status

**Comment by amcdavid** [comment]
Looks like there is some issue with your development stack. Can you compile
other packages that use RcppArmadillo? Does `install.packages('activegp',
type='source')` work, for example?

**Comment by galaxywall** [comment]
It did work... I got the message "The downloaded source packages are in XXX".

**Comment by amcdavid** [comment]
Did you see evidence that they compiled and installed OK (eg, output from g++?)
I don't have access to a windows machine currently, but some of your output makes my suspicious that you have mixed versions of Rtools (3.5) and R 3.6.  

I can confirm that I can compile and install HurdleNormal fine on Mac and Linux.

**Comment by galaxywall** [comment]
I have attached the output below. Note that I tried uninstalled every R stuff in my laptop (there were indeed mixed versions of Rtools) and then reinstalled everything, but I kept getting the "non-zero exit status" error when trying installing HurdleNormal.

> install.packages('activegp',type='source')
Installing package into ‘C:/Users/galaxywall/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/activegp_1.0.4.tar.gz'
Content type 'application/x-gzip' length 36632 bytes (35 KB)
downloaded 35 KB

* installing *source* package 'activegp' ...
** package 'activegp' successfully unpacked and MD5 sums checked
** using staged installation
** libs

*** arch - i386
"C:/Users/galaxywall/Documents/R/win-library/4.0/lib/mingw32/bin/"g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG  -I'C:/Users/galaxywall/Documents/R/win-library/4.0/Rcpp/include' -I'C:/Users/galaxywall/Documents/R/win-library/4.0/RcppArmadillo/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c C_GPcpp.cpp -o C_GPcpp.o
"C:/Users/galaxywall/Documents/R/win-library/4.0/lib/mingw32/bin/"g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG  -I'C:/Users/galaxywall/Documents/R/win-library/4.0/Rcpp/include' -I'C:/Users/galaxywall/Documents/R/win-library/4.0/RcppArmadillo/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c RcppExports.cpp -o RcppExports.o
"C:/Users/galaxywall/Documents/R/win-library/4.0/lib/mingw32/bin/"g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG  -I'C:/Users/galaxywall/Documents/R/win-library/4.0/Rcpp/include' -I'C:/Users/galaxywall/Documents/R/win-library/4.0/RcppArmadillo/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c hetGP_funcs.cpp -o hetGP_funcs.o
"C:/Users/galaxywall/Documents/R/win-library/4.0/lib/mingw32/bin/"g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG  -I'C:/Users/galaxywall/Documents/R/win-library/4.0/Rcpp/include' -I'C:/Users/galaxywall/Documents/R/win-library/4.0/RcppArmadillo/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c kernelexps.cpp -o kernelexps.o
C:/Users/galaxywall/Documents/R/win-library/4.0/lib/mingw32/bin/g++ -std=gnu++11 -shared -s -static-libgcc -o activegp.dll tmp.def C_GPcpp.o RcppExports.o hetGP_funcs.o kernelexps.o -LC:/PROGRA~1/R/R-40~1.2/bin/i386 -lRlapack -LC:/PROGRA~1/R/R-40~1.2/bin/i386 -lRblas -lgfortran -lm -lquadmath -LC:/PROGRA~1/R/R-40~1.2/bin/i386 -lR
installing to C:/Users/galaxywall/Documents/R/win-library/4.0/00LOCK-activegp/00new/activegp/libs/i386

*** arch - x64
"C:/Users/galaxywall/Documents/R/win-library/4.0/lib/mingw64/bin/"g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG  -I'C:/Users/galaxywall/Documents/R/win-library/4.0/Rcpp/include' -I'C:/Users/galaxywall/Documents/R/win-library/4.0/RcppArmadillo/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c C_GPcpp.cpp -o C_GPcpp.o
"C:/Users/galaxywall/Documents/R/win-library/4.0/lib/mingw64/bin/"g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG  -I'C:/Users/galaxywall/Documents/R/win-library/4.0/Rcpp/include' -I'C:/Users/galaxywall/Documents/R/win-library/4.0/RcppArmadillo/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c RcppExports.cpp -o RcppExports.o
"C:/Users/galaxywall/Documents/R/win-library/4.0/lib/mingw64/bin/"g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG  -I'C:/Users/galaxywall/Documents/R/win-library/4.0/Rcpp/include' -I'C:/Users/galaxywall/Documents/R/win-library/4.0/RcppArmadillo/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c hetGP_funcs.cpp -o hetGP_funcs.o
"C:/Users/galaxywall/Documents/R/win-library/4.0/lib/mingw64/bin/"g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG  -I'C:/Users/galaxywall/Documents/R/win-library/4.0/Rcpp/include' -I'C:/Users/galaxywall/Documents/R/win-library/4.0/RcppArmadillo/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c kernelexps.cpp -o kernelexps.o
C:/Users/galaxywall/Documents/R/win-library/4.0/lib/mingw64/bin/g++ -std=gnu++11 -shared -s -static-libgcc -o activegp.dll tmp.def C_GPcpp.o RcppExports.o hetGP_funcs.o kernelexps.o -LC:/PROGRA~1/R/R-40~1.2/bin/x64 -lRlapack -LC:/PROGRA~1/R/R-40~1.2/bin/x64 -lRblas -lgfortran -lm -lquadmath -LC:/PROGRA~1/R/R-40~1.2/bin/x64 -lR
installing to C:/Users/galaxywall/Documents/R/win-library/4.0/00LOCK-activegp/00new/activegp/libs/x64
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'activegp'
    finding HTML links ... done
    C_GP                                    html  
    C_GP_ci                                 html  
    C_GP_cpp                                html  
    C_Q                                     html  
    C_tr                                    html  
    C_var                                   html  
    C_var2                                  html  
    W_kappa_ij                              html  
    W_kappa_ij2                             html  
    W_kappa_ij_up                           html  
    activegp                                html  
    d1                                      html  
    domain_to_R                             html  
    domain_to_unit                          html  
    get_betagamma                           html  
    grad_W_kappa_ij2                        html  
    grad_W_kappa_ij2_w2                     html  
    grad_est_subspace                       html  
    logLikHessian                           html  
    n11_2_01                                html  
    print.const_C                           html  
    subspace_dist                           html  
    update.const_C                          html  
    update_C2                               html  
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
** testing if installed package keeps a record of temporary installation path
* DONE (activegp)

The downloaded source packages are in
	‘C:\Users\galaxywall\AppData\Local\Temp\RtmpqW8S3V\downloaded_packages’

**Comment by amcdavid** [comment]
Ok, that looks like reasonable output from activegp, so I think we can rule out toolchain issues now.

 What error message do that you get now from compiling HurdleNormal with the R4.0 stack?  "non-zero exit status" isn't specific enough for me to help -- as I've said, HurdleNormal compiles fine on the systems I have access to. I don't have ready access to a windows machine so I am relying on your report to understand what might be going on.

**Comment by galaxywall** [comment]
I just installed Ubuntu in my computer and was able to move on to the body of your simulation codes. By the way, could you please tell me where I can find your data for T follicular helper cells? I can only locate your Shalek data from GitHub.

According to the corresponding paper, you used Gaussian based on the rough observation that the empirical distribution of log-transformed values is generally symmetric. Did you just observe that by making a density plot for each column?

**Comment by amcdavid** [comment]
Regarding normality, I think at some point we did some goodness of fit testing in the preparation of writing Finak et al 2015 though nothing that made it into the paper.  This was a while ago and I'm a bit fuzzy on the details, so make what of that you will.  With sufficient same size, I would be astonished if you could accept normality marginally.  And of course, being marginally normal certainly doesn't mean that the distribution is conditionally normal (unless besides the margins, each and every other linear combination is normal...)

Let me know what your email is, and I will send you the T follicular helper cells.  I am not able to post them publicly but happy to share upon request.

**Comment by galaxywall** [comment]
My email address is: harvey961001@gmail.com. Thanks.

**Comment by galaxywall** [comment]
I just got the error message "object 'contaminate' not found" when running the for loop containing "contam = switch(modelArgs[i,'contam'], t=contaminate, none=NA, selection=selectionModel)" in your "simulations.R" file. Do you have an idea what that error is about? Is it related to the source() and install() from the previous lines?

**Comment by amcdavid** [comment]
You probably need to source('simulation-library.R'):
https://github.com/amcdavid/HurdleNormal/search?q=contaminate&unscoped_q=contaminate
